[package]
name = "rsdocs2docset"
version = "0.1.0"
authors = ["Daniel Bornkessel"]

[[bin]]
name = "rsdocs2docset"
doc = false

[dependencies]
html5ever = "*"
html5ever-atoms = "*"
string_cache = "*"
sqlite = "*"
tendril = "*"
clap = "*"
quick-error = "*"
regex = "*"
url = "*"
