#!/bin/bash -e
dir=~/.rs-docsets
mkdir -p ${dir}

while [ $# -gt 0 ]
do
  package=$1

  cd ${dir}
  test -e Cargo.toml || cargo init --name dummy
  grep "^${package} = \"*\"" Cargo.toml || echo "${package} = \"*\"" >> Cargo.toml
  cargo generate-lockfile
  export OPENSSL_INCLUDE_DIR=$(ls -td /usr/local/Cellar/openssl/*/include|head -n1)
  rm -rf target/doc
  rustup run nightly cargo doc --no-deps -p ${package}
  rm -rf ${package}.docset
  rsdocs2docset --rsdoc target/doc --name ${package}
  open ${package}.docset
  shift
done
