#!/bin/bash -e

version=$(cat VERSION)

sed -i "" -e "s/^version =.*$/version = \"${version}\"/g" Cargo.toml
cargo generate-lockfile
git commit -v Cargo.toml Cargo.lock VERSION
git tag v${version}
git push --tags && git push
